version: '3'
volumes:
  data:

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
       POSTGRES_PASSWORD: postgres
       POSTGRES_USERNAME: postgres
       POSTGRES_DB: Todo
    ports:
      - 5432:5432
    volumes:
      - ./db-postgres:/var/lib/postgresql
    restart: always